version: '3'

services:
  app:
    image: "soksbrian/imagescarousel_service:1.0"
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  database:
    image: mongo:4.0.0
    ports:
      - '27017:27017'
